version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - chat-service
      - user-service
      - analytics-service

  chat-service:
    build: ./chat-service
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=chatdb
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=chatdb
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - postgres

  analytics-service:
    build: ./analytics-service
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=chatdb
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: