version: '3.8'

services:
  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - chat-service
      - user-service
      - analytics-service

  chat-service:
    build: ../backend/chat-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/chatdb?schema=public
    depends_on:
      - postgres

  user-service:
    build: ../backend/user-service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/chatdb?schema=public
    depends_on:
      - postgres

  analytics-service:
    build: ../backend/analytics-service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/chatdb?schema=public
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: